name: ErydanRandomChest
version: 1.0
author: NaiKyzZ
main: fr.naikyzz.erydanrandomchest.ErydanRandomChest
commands:
  rc:
    description: Petites aides pour la commande
    permission: rc.use
  rcr:
    description: Fait spawn un coffre random
  rcp:
    description: Fait spawn un coffre à la position de celui qui effectue la commande
