name: ErydanRandomChest
author: NaiKyzZ

#Messages du plugin
messages:
  reload: "&eErydanRandomChest a bien été reload !"

#Configuration des items qui vont apparaître dans le coffre
chest:
  item:
    1:
      material:
        DIAMOND_SWORD
      amount:
        1
      enchanted: #False if nothing
        true
      enchants:
        DAMAGE_ALL 2
    2:
      material:
        APPLE
      amount:
        12
      enchanted:
        false