name: ErydanRandomChest
author: NaiKyzZ

#Messages du plugin
messages:
  reload: "&eErydanRandomChest a bien été reload !"

#Configuration des items qui vont apparaître dans le coffre
#Liste des enchantements https://helpch.at/docs/1.8.8/index.html?org/bukkit/event/enchantment/EnchantItemEvent.html
chest:
  maxWorld: 7500
  minWorld: -7500
  maxitemloot:
    7
  item:
    1:
      material:
        DIAMOND_SWORD
      amount:
        1
      chance:
        100
      enchanted: #False if nothing or if you cant enchant this material
        true
      enchants:
        -DAMAGE_ALL 2
        -FIRE_ASPECT 1
        -DAMAGE_UNDEAD 5
      sub:
        false
    2:
      material:
        GOLDEN_APPLE
      amount:
        12
      chance:
        100
      enchanted:
        false
      sub:
        true
      subname:
        1
    3:
      material:
        IRON_HELMET
      amount:
        1
      chance:
        100
      enchanted:
        false
      sub:
        false
    4:
      material:
        TNT
      amount:
        1
      chance:
        100
      enchanted:
        false
      sub:
        false
    5:
      material:
        IRON_CHESTPLATE
      amount:
        1
      chance:
        100
      enchanted:
        false
      sub:
        false
    6:
      material:
        IRON_SWORD
      amount:
        1
      chance:
        100
      enchanted:
        false
      sub:
        false
    7:
      material:
        DIAMOND_PICKAXE
      amount:
        1
      chance:
        100
      enchanted:
        false
      sub:
        false
    8:
      material:
        IRON_SHOVEL
      amount:
        1
      chance:
        100
      enchanted:
        false
      sub:
        false
      subname:
        1