name: ErydanRandomChest
author: NaiKyzZ

#Messages du plugin
messages:
  reload: "&eErydanRandomChest a bien été reload !"

#Configuration des items qui vont apparaître dans le coffre
chest:
    type:
      - APPLE 16
      - GOLDEN_APPLE 16 1
      - DIAMOND_SWORD 1
      - BEACON 1
# - ==: org.bukkit.inventory.ItemStack
#  type: STONE

